import type { Card } from "../types";

/** Popular printings used when the live catalog is unreachable. */
export const LOCAL_CARDS: Card[] = [
  { id: "base1-58", name: "Pikachu", image: "https://images.pokemontcg.io/base1/58.png", setName: "Base", number: "58" },
  { id: "base1-4", name: "Charizard", image: "https://images.pokemontcg.io/base1/4.png", setName: "Base", number: "4" },
  { id: "base1-15", name: "Venusaur", image: "https://images.pokemontcg.io/base1/15.png", setName: "Base", number: "15" },
  { id: "base1-2", name: "Blastoise", image: "https://images.pokemontcg.io/base1/2.png", setName: "Base", number: "2" },
  { id: "sv1-80", name: "Miraidon", image: "https://images.pokemontcg.io/sv1/80.png", setName: "Scarlet & Violet", number: "80" },
  { id: "sv1-81", name: "Miraidon ex", image: "https://images.pokemontcg.io/sv1/81.png", setName: "Scarlet & Violet", number: "81" },
  { id: "neo1-9", name: "Lugia", image: "https://images.pokemontcg.io/neo1/9.png", setName: "Neo Genesis", number: "9" },
  { id: "neo2-13", name: "Umbreon", image: "https://images.pokemontcg.io/neo2/13.png", setName: "Neo Discovery", number: "13" },
  { id: "neo2-1", name: "Espeon", image: "https://images.pokemontcg.io/neo2/1.png", setName: "Neo Discovery", number: "1" },
  { id: "pop3-3", name: "Jolteon", image: "https://images.pokemontcg.io/pop3/3.png", setName: "POP Series 3", number: "3" },
  { id: "dp5-5", name: "Glaceon", image: "https://images.pokemontcg.io/dp5/5.png", setName: "Majestic Dawn", number: "5" },
  { id: "pop6-2", name: "Lucario", image: "https://images.pokemontcg.io/pop6/2.png", setName: "POP Series 6", number: "2" },
  { id: "dpp-DP50", name: "Arceus", image: "https://images.pokemontcg.io/dpp/DP50.png", setName: "DP Black Star Promos", number: "DP50" },
  { id: "dp3-3", name: "Charizard", image: "https://images.pokemontcg.io/dp3/3.png", setName: "Secret Wonders", number: "3" },
  { id: "basep-1", name: "Pikachu", image: "https://images.pokemontcg.io/basep/1.png", setName: "Wizards Black Star Promos", number: "1" },
  { id: "mcd19-6", name: "Pikachu", image: "https://images.pokemontcg.io/mcd19/6.png", setName: "McDonald's Collection 2019", number: "6" },
  { id: "si1-1", name: "Mew", image: "https://images.pokemontcg.io/si1/1.png", setName: "Southern Islands", number: "1" },
  { id: "pop4-4", name: "Mew", image: "https://images.pokemontcg.io/pop4/4.png", setName: "POP Series 4", number: "4" },
  { id: "hgss3-10", name: "Umbreon", image: "https://images.pokemontcg.io/hgss3/10.png", setName: "HS—Undaunted", number: "10" },
  { id: "ex11-17", name: "Umbreon δ", image: "https://images.pokemontcg.io/ex11/17.png", setName: "Delta Species", number: "17" },
  { id: "ex9-4", name: "Gardevoir", image: "https://images.pokemontcg.io/ex9/4.png", setName: "Emerald", number: "4" },
  { id: "ex11-6", name: "Gardevoir δ", image: "https://images.pokemontcg.io/ex11/6.png", setName: "Delta Species", number: "6" },
  { id: "swsh2-91", name: "Dragapult", image: "https://images.pokemontcg.io/swsh2/91.png", setName: "Rebel Clash", number: "91" },
  { id: "swsh2-92", name: "Dragapult V", image: "https://images.pokemontcg.io/swsh2/92.png", setName: "Rebel Clash", number: "92" },
  { id: "pop5-2", name: "Lugia", image: "https://images.pokemontcg.io/pop5/2.png", setName: "POP Series 5", number: "2" },
  { id: "hsp-HGSS02", name: "Lugia", image: "https://images.pokemontcg.io/hsp/HGSS02.png", setName: "HGSS Black Star Promos", number: "HGSS02" },
  { id: "ru1-1", name: "Venusaur", image: "https://images.pokemontcg.io/ru1/1.png", setName: "Pokémon Rumble", number: "1" },
  { id: "sm9-1", name: "Celebi & Venusaur-GX", image: "https://images.pokemontcg.io/sm9/1.png", setName: "Team Up", number: "1" },
  { id: "pl1-2", name: "Blastoise", image: "https://images.pokemontcg.io/pl1/2.png", setName: "Platinum", number: "2" },
  { id: "dp3-2", name: "Blastoise", image: "https://images.pokemontcg.io/dp3/2.png", setName: "Secret Wonders", number: "2" },
  { id: "det1-4", name: "Charmander", image: "https://images.pokemontcg.io/det1/4.png", setName: "Detective Pikachu", number: "4" },
  { id: "sm75-1", name: "Charmander", image: "https://images.pokemontcg.io/sm75/1.png", setName: "Dragon Majesty", number: "1" },
  { id: "det1-1", name: "Bulbasaur", image: "https://images.pokemontcg.io/det1/1.png", setName: "Detective Pikachu", number: "1" },
  { id: "bw5-1", name: "Bulbasaur", image: "https://images.pokemontcg.io/bw5/1.png", setName: "Dark Explorers", number: "1" },
  { id: "bw10-14", name: "Squirtle", image: "https://images.pokemontcg.io/bw10/14.png", setName: "Plasma Blast", number: "14" },
  { id: "pop4-14", name: "Squirtle", image: "https://images.pokemontcg.io/pop4/14.png", setName: "POP Series 4", number: "14" },
  { id: "basep-3", name: "Mewtwo", image: "https://images.pokemontcg.io/basep/3.png", setName: "Wizards Black Star Promos", number: "3" },
  { id: "ru1-9", name: "Mewtwo", image: "https://images.pokemontcg.io/ru1/9.png", setName: "Pokémon Rumble", number: "9" },
  { id: "ex12-5", name: "Gengar", image: "https://images.pokemontcg.io/ex12/5.png", setName: "Legend Maker", number: "5" },
  { id: "base3-5", name: "Gengar", image: "https://images.pokemontcg.io/base3/5.png", setName: "Fossil", number: "5" },
  { id: "smp-SM05", name: "Snorlax-GX", image: "https://images.pokemontcg.io/smp/SM05.png", setName: "SM Black Star Promos", number: "SM05" },
  { id: "base2-11", name: "Snorlax", image: "https://images.pokemontcg.io/base2/11.png", setName: "Jungle", number: "11" },
  { id: "ex11-3", name: "Dragonite δ", image: "https://images.pokemontcg.io/ex11/3.png", setName: "Delta Species", number: "3" },
  { id: "base3-4", name: "Dragonite", image: "https://images.pokemontcg.io/base3/4.png", setName: "Fossil", number: "4" },
  { id: "hgss1-4", name: "Gyarados", image: "https://images.pokemontcg.io/hgss1/4.png", setName: "HeartGold & SoulSilver", number: "4" },
  { id: "gym2-5", name: "Giovanni's Gyarados", image: "https://images.pokemontcg.io/gym2/5.png", setName: "Gym Challenge", number: "5" },
  { id: "mcd19-12", name: "Eevee", image: "https://images.pokemontcg.io/mcd19/12.png", setName: "McDonald's Collection 2019", number: "12" },
  { id: "basep-11", name: "Eevee", image: "https://images.pokemontcg.io/basep/11.png", setName: "Wizards Black Star Promos", number: "11" },
  { id: "ex11-4", name: "Espeon δ", image: "https://images.pokemontcg.io/ex11/4.png", setName: "Delta Species", number: "4" },
  { id: "neo4-4", name: "Dark Espeon", image: "https://images.pokemontcg.io/neo4/4.png", setName: "Neo Destiny", number: "4" },
  { id: "pop3-6", name: "Vaporeon", image: "https://images.pokemontcg.io/pop3/6.png", setName: "POP Series 3", number: "6" },
  { id: "base6-9", name: "Dark Vaporeon", image: "https://images.pokemontcg.io/base6/9.png", setName: "Legendary Collection", number: "9" },
  { id: "pop3-2", name: "Flareon", image: "https://images.pokemontcg.io/pop3/2.png", setName: "POP Series 3", number: "2" },
  { id: "ex11-5", name: "Flareon δ", image: "https://images.pokemontcg.io/ex11/5.png", setName: "Delta Species", number: "5" },
  { id: "bw5-6", name: "Leafeon", image: "https://images.pokemontcg.io/bw5/6.png", setName: "Dark Explorers", number: "6" },
  { id: "sm5-13", name: "Leafeon-GX", image: "https://images.pokemontcg.io/sm5/13.png", setName: "Ultra Prism", number: "13" },
  { id: "xyp-XY04", name: "Sylveon", image: "https://images.pokemontcg.io/xyp/XY04.png", setName: "XY Black Star Promos", number: "XY04" },
  { id: "sma-SV76", name: "Sylveon-GX", image: "https://images.pokemontcg.io/sma/SV76.png", setName: "Hidden Fates Shiny Vault", number: "SV76" },
  { id: "pop1-3", name: "Rayquaza", image: "https://images.pokemontcg.io/pop1/3.png", setName: "POP Series 1", number: "3" },
  { id: "ex9-9", name: "Rayquaza", image: "https://images.pokemontcg.io/ex9/9.png", setName: "Emerald", number: "9" },
  { id: "det1-9", name: "Greninja", image: "https://images.pokemontcg.io/det1/9.png", setName: "Detective Pikachu", number: "9" },
  { id: "xy0-14", name: "Greninja", image: "https://images.pokemontcg.io/xy0/14.png", setName: "Kalos Starter Set", number: "14" },
  { id: "pop9-1", name: "Garchomp", image: "https://images.pokemontcg.io/pop9/1.png", setName: "POP Series 9", number: "1" },
  { id: "pl3-5", name: "Garchomp", image: "https://images.pokemontcg.io/pl3/5.png", setName: "Supreme Victors", number: "5" },
  { id: "neo4-11", name: "Dark Tyranitar", image: "https://images.pokemontcg.io/neo4/11.png", setName: "Neo Destiny", number: "11" },
  { id: "ex11-16", name: "Tyranitar δ", image: "https://images.pokemontcg.io/ex11/16.png", setName: "Delta Species", number: "16" },
  { id: "dp1-1", name: "Dialga", image: "https://images.pokemontcg.io/dp1/1.png", setName: "Diamond & Pearl", number: "1" },
  { id: "col1-3", name: "Dialga", image: "https://images.pokemontcg.io/col1/3.png", setName: "Call of Legends", number: "3" },
  { id: "pl1-12", name: "Palkia G", image: "https://images.pokemontcg.io/pl1/12.png", setName: "Platinum", number: "12" },
  { id: "dp1-11", name: "Palkia", image: "https://images.pokemontcg.io/dp1/11.png", setName: "Diamond & Pearl", number: "11" },
  { id: "pl1-9", name: "Giratina", image: "https://images.pokemontcg.io/pl1/9.png", setName: "Platinum", number: "9" },
  { id: "pl1-10", name: "Giratina", image: "https://images.pokemontcg.io/pl1/10.png", setName: "Platinum", number: "10" },
  { id: "hgss4-3", name: "Celebi", image: "https://images.pokemontcg.io/hgss4/3.png", setName: "HS—Triumphant", number: "3" },
  { id: "dp4-3", name: "Darkrai", image: "https://images.pokemontcg.io/dp4/3.png", setName: "Great Encounters", number: "3" },
  { id: "dp4-4", name: "Darkrai", image: "https://images.pokemontcg.io/dp4/4.png", setName: "Great Encounters", number: "4" },
  { id: "base4-1", name: "Alakazam", image: "https://images.pokemontcg.io/base4/1.png", setName: "Base Set 2", number: "1" },
  { id: "base5-1", name: "Dark Alakazam", image: "https://images.pokemontcg.io/base5/1.png", setName: "Team Rocket", number: "1" },
  { id: "gym2-6", name: "Giovanni's Machamp", image: "https://images.pokemontcg.io/gym2/6.png", setName: "Gym Challenge", number: "6" },
  { id: "ex12-9", name: "Machamp", image: "https://images.pokemontcg.io/ex12/9.png", setName: "Legend Maker", number: "9" },
  { id: "sv1-124", name: "Koraidon", image: "https://images.pokemontcg.io/sv1/124.png", setName: "Scarlet & Violet", number: "124" },
  { id: "sv1-125", name: "Koraidon ex", image: "https://images.pokemontcg.io/sv1/125.png", setName: "Scarlet & Violet", number: "125" },
  { id: "sv6-24", name: "Teal Mask Ogerpon", image: "https://images.pokemontcg.io/sv6/24.png", setName: "Twilight Masquerade", number: "24" },
  { id: "sv6-25", name: "Teal Mask Ogerpon ex", image: "https://images.pokemontcg.io/sv6/25.png", setName: "Twilight Masquerade", number: "25" },
  { id: "si1-8", name: "Jigglypuff", image: "https://images.pokemontcg.io/si1/8.png", setName: "Southern Islands", number: "8" },
  { id: "basep-7", name: "Jigglypuff", image: "https://images.pokemontcg.io/basep/7.png", setName: "Wizards Black Star Promos", number: "7" },
  { id: "si1-4", name: "Togepi", image: "https://images.pokemontcg.io/si1/4.png", setName: "Southern Islands", number: "4" },
  { id: "mcd16-9", name: "Togepi", image: "https://images.pokemontcg.io/mcd16/9.png", setName: "McDonald's Collection 2016", number: "9" },
  { id: "sv3-62", name: "Palafin", image: "https://images.pokemontcg.io/sv3/62.png", setName: "Obsidian Flames", number: "62" },
  { id: "sv3-200", name: "Palafin", image: "https://images.pokemontcg.io/sv3/200.png", setName: "Obsidian Flames", number: "200" },
  { id: "swshp-SWSH015", name: "Cinderace V", image: "https://images.pokemontcg.io/swshp/SWSH015.png", setName: "SWSH Black Star Promos", number: "SWSH015" },
  { id: "swsh1-34", name: "Cinderace", image: "https://images.pokemontcg.io/swsh1/34.png", setName: "Sword & Shield", number: "34" },
  { id: "base1-9", name: "Magneton", image: "https://images.pokemontcg.io/base1/9.png", setName: "Base", number: "9" },
  { id: "swsh7-95", name: "Umbreon VMAX", image: "https://images.pokemontcg.io/swsh7/95.png", setName: "Evolving Skies", number: "95" },
];
